//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УЧЁТ_МЕДИЦИНСКИХ_ДАННЫХ_СТУДЕНТОВ.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudentSurname { get; set; }
        public string StudentName { get; set; }
        public string StudentPatronymic { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int GroupID { get; set; }
        public int StatusID { get; set; }
        public string StudentRegAddress { get; set; }
        public string StudentFactAddress { get; set; }
        public int GenderID { get; set; }
        public int ContractID { get; set; }
        public int EduFormID { get; set; }
        public string PolisNumber { get; set; }
        public string PolisGiven { get; set; }
        public int DormID { get; set; }
        public Nullable<System.DateTime> FluorDate { get; set; }
        public int GrippStatusID { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> FluorDiff { get; set; }
        public int VacCertID { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Dorm Dorm { get; set; }
        public virtual EduForm EduForm { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual GrippStatus GrippStatus { get; set; }
        public virtual Group Group { get; set; }
        public virtual Status Status { get; set; }
        public virtual VacCert VacCert { get; set; }
    }
}
